In [9]:
# install the packages we need

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
# load the data

NBA19 = pd.read_excel("Assignment Data/NBA2019odds.xlsx")
NBA19

team               opponent  day  month  year  winodds  \
0     Golden State Warriors        Houston Rockets    4      1  2019     1.27   
1           Houston Rockets  Golden State Warriors    4      1  2019     3.92   
2           New York Knicks     Washington Wizards   17      1  2019     3.52   
3        Washington Wizards        New York Knicks   17      1  2019     1.32   
4            Boston Celtics     Los Angeles Lakers    8      2  2019     1.24   
...                     ...                    ...  ...    ...   ...      ...   
2455  Golden State Warriors      Charlotte Hornets    1      4  2019     1.13   
2456       Dallas Mavericks              Utah Jazz   15     11  2018     2.75   
2457              Utah Jazz       Dallas Mavericks   15     11  2018     1.47   
2458         Boston Celtics          Chicago Bulls    9     12  2018     1.28   
2459          Chicago Bulls         Boston Celtics    9     12  2018     3.80   

      loseodds  teampts  oppopts  diff  overtime  home  \
0         3.92      134      135     1         1     1   
1         1.27      135      134     1         1     0   
2         1.32      100      101     1         0     0   
3         3.52      101      100     1         0     1   
4         4.31      128      129     1         0     1   
...        ...      ...      ...   ...       ...   ...   
2455      6.42      137       90    47         0     1   
2456      1.47      118       68    50         0     1   
2457      2.75       68      118    50         0     0   
2458      3.80      133       77    56         0     0   
2459      1.28       77      133    56         0     1   

                                Game(home-away)     HAscore  win prob  win  
0       Golden State Warriors - Houston Rockets  134:135 ET  0.755299    0  
1       Golden State Warriors - Houston Rockets  134:135 ET  0.244701    1  
2          Washington Wizards - New York Knicks     101:100  0.272727    0  
3          Washington Wizards - New York Knicks     101:100  0.727273    1  
4           Boston Celtics - Los Angeles Lakers     128:129  0.776577    0  
...                                         ...         ...       ...  ...  
2455  Golden State Warriors - Charlotte Hornets      137:90  0.850331    1  
2456               Dallas Mavericks - Utah Jazz      118:68  0.348341    1  
2457               Dallas Mavericks - Utah Jazz      118:68  0.651659    0  
2458             Chicago Bulls - Boston Celtics      77:133  0.748031    1  
2459             Chicago Bulls - Boston Celtics      77:133  0.251969    0  

[2460 rows x 16 columns]

Calculate the implied win probability based on the bookmaker odds

In [11]:
# win odds
# (a) taking the reciprocal of the odds
# (b) dividing by the sum of all probabilities
# (because of the overround we have to scale the probabilities so that they add up to 100%).
NBA19['winprob']= 1/(NBA19['winodds'])/(1/(NBA19['winodds'])+ 1/(NBA19['loseodds']))
NBA19

team               opponent  day  month  year  winodds  \
0     Golden State Warriors        Houston Rockets    4      1  2019     1.27   
1           Houston Rockets  Golden State Warriors    4      1  2019     3.92   
2           New York Knicks     Washington Wizards   17      1  2019     3.52   
3        Washington Wizards        New York Knicks   17      1  2019     1.32   
4            Boston Celtics     Los Angeles Lakers    8      2  2019     1.24   
...                     ...                    ...  ...    ...   ...      ...   
2455  Golden State Warriors      Charlotte Hornets    1      4  2019     1.13   
2456       Dallas Mavericks              Utah Jazz   15     11  2018     2.75   
2457              Utah Jazz       Dallas Mavericks   15     11  2018     1.47   
2458         Boston Celtics          Chicago Bulls    9     12  2018     1.28   
2459          Chicago Bulls         Boston Celtics    9     12  2018     3.80   

      loseodds  teampts  oppopts  diff  overtime  home  \
0         3.92      134      135     1         1     1   
1         1.27      135      134     1         1     0   
2         1.32      100      101     1         0     0   
3         3.52      101      100     1         0     1   
4         4.31      128      129     1         0     1   
...        ...      ...      ...   ...       ...   ...   
2455      6.42      137       90    47         0     1   
2456      1.47      118       68    50         0     1   
2457      2.75       68      118    50         0     0   
2458      3.80      133       77    56         0     0   
2459      1.28       77      133    56         0     1   

                                Game(home-away)     HAscore  win prob  win  \
0       Golden State Warriors - Houston Rockets  134:135 ET  0.755299    0   
1       Golden State Warriors - Houston Rockets  134:135 ET  0.244701    1   
2          Washington Wizards - New York Knicks     101:100  0.272727    0   
3          Washington Wizards - New York Knicks     101:100  0.727273    1   
4           Boston Celtics - Los Angeles Lakers     128:129  0.776577    0   
...                                         ...         ...       ...  ...   
2455  Golden State Warriors - Charlotte Hornets      137:90  0.850331    1   
2456               Dallas Mavericks - Utah Jazz      118:68  0.348341    1   
2457               Dallas Mavericks - Utah Jazz      118:68  0.651659    0   
2458             Chicago Bulls - Boston Celtics      77:133  0.748031    1   
2459             Chicago Bulls - Boston Celtics      77:133  0.251969    0   

       winprob  
0     0.755299  
1     0.244701  
2     0.272727  
3     0.727273  
4     0.776577  
...        ...  
2455  0.850331  
2456  0.348341  
2457  0.651659  
2458  0.748031  
2459  0.251969  

[2460 rows x 17 columns]

Drop from the data all games for which home = 0

In [12]:
NBA19 = NBA19[NBA19['home'] != 0]

What is the correlation between the home team win probability and home team wins across the entire 2018/19 season? 

In [20]:
np.corrcoef( NBA19["win"], NBA19["winprob"])

array([[1.        , 0.39652887],
       [0.39652887, 1.        ]])

#### Subsets

1. One for games where the absolute value of the points difference is less than 9 and another for games where the points difference is greater than 9 (9 is the median points difference in the data)

In [13]:
less_than_9 = NBA19[NBA19['diff'] < 9]
more_than_9 = NBA19[NBA19['diff'] > 9]

What is the correlation between the home team win probability and home team wins for games where the points difference was less than 9?

In [21]:
np.corrcoef( less_than_9["win"], less_than_9["winprob"])

array([[1.        , 0.19811648],
       [0.19811648, 1.        ]])

What is the correlation between the home team win probability and home team wins for games where the points difference was greater than 9?

In [22]:
np.corrcoef( more_than_9["win"], more_than_9["winprob"])

array([[1.        , 0.57647206],
       [0.57647206, 1.        ]])

2. One for games that went to overtime, and one for games which finished in regulation time

In [14]:
overtime_games = NBA19[NBA19['overtime'] == 1]
regular_games = NBA19[NBA19['overtime'] == 0]

What is the correlation between the home team win probability and home team wins for games where the game went to overtime?

In [23]:
np.corrcoef( overtime_games["win"], overtime_games["winprob"])

array([[1.        , 0.03225853],
       [0.03225853, 1.        ]])

What is the correlation between the home team win probability and home team wins for games where the game was finished in regular time?

In [24]:
np.corrcoef( regular_games["win"], regular_games["winprob"])

array([[1.       , 0.4144347],
       [0.4144347, 1.       ]])

3. One for games played in calendar year 2018, one for games played in calendar year 2019

In [16]:
games_2018 = NBA19[NBA19['year'] == 2018]
games_2019 = NBA19[NBA19['year'] == 2019]

What is the correlation between the home team win probability and home team wins for games where the game was played in calendar year 2018?

In [25]:
np.corrcoef( games_2018["win"], games_2018["winprob"])

array([[1.        , 0.33824657],
       [0.33824657, 1.        ]])

What is the correlation between the home team win probability and home team wins for games where the game was played in calendar year 2019?

In [26]:
np.corrcoef( games_2019["win"], games_2019["winprob"])

array([[1.        , 0.43797601],
       [0.43797601, 1.        ]])

4. One for each month in the data (October to April)

In [19]:
months = [10,11,12,1,2,3,4]

for month in months:
    month_subset = NBA19[NBA19['month'] == month]
    vars()[f'game_month_{month}'] = month_subset
    vars()[f'game_month_{month}']
    
## vars() is a built-in function that returns the __dict__ attribute of the module or class,
## or the current local symbol table

game_month_10

team               opponent  day  month  year  \
52         Charlotte Hornets        Milwaukee Bucks   18     10  2018   
54           Detroit Pistons     Philadelphia 76ers   24     10  2018   
56        Los Angeles Lakers      San Antonio Spurs   23     10  2018   
58                Miami Heat      Charlotte Hornets   21     10  2018   
61        Philadelphia 76ers          Orlando Magic   21     10  2018   
...                      ...                    ...  ...    ...   ...   
2322         New York Knicks  Golden State Warriors   27     10  2018   
2342       Charlotte Hornets          Chicago Bulls   27     10  2018   
2355  Minnesota Timberwolves        Milwaukee Bucks   27     10  2018   
2381    Los Angeles Clippers     Washington Wizards   29     10  2018   
2382           Orlando Magic      Charlotte Hornets   20     10  2018   

      winodds  loseodds  teampts  oppopts  diff  overtime  home  \
52       2.37      1.61      112      113     1         0     1   
54       1.96      1.88      133      132     1         1     1   
56       1.85      1.99      142      143     1         1     1   
58       1.61      2.38      112      113     1         0     1   
61       1.07      9.18      116      115     1         0     1   
...       ...       ...      ...      ...   ...       ...   ...   
2322     7.59      1.10      100      128    28         0     1   
2342     1.17      5.47      135      106    29         0     1   
2355     2.15      1.73       95      125    30         0     1   
2381     1.60      2.40      136      104    32         0     1   
2382     2.03      1.82       88      120    32         0     1   

                                Game(home-away)     HAscore  win prob  win  \
52          Charlotte Hornets - Milwaukee Bucks     112:113  0.404523    0   
54         Detroit Pistons - Philadelphia 76ers  133:132 ET  0.489583    1   
56       Los Angeles Lakers - San Antonio Spurs  142:143 ET  0.518229    0   
58               Miami Heat - Charlotte Hornets     112:113  0.596491    0   
61           Philadelphia 76ers - Orlando Magic     116:115  0.895610    1   
...                                         ...         ...       ...  ...   
2322    New York Knicks - Golden State Warriors     100:128  0.126582    0   
2342          Charlotte Hornets - Chicago Bulls     135:106  0.823795    1   
2355   Minnesota Timberwolves - Milwaukee Bucks      95:125  0.445876    0   
2381  Los Angeles Clippers - Washington Wizards     136:104  0.600000    1   
2382          Orlando Magic - Charlotte Hornets      88:120  0.472727    0   

       winprob  
52    0.404523  
54    0.489583  
56    0.518229  
58    0.596491  
61    0.895610  
...        ...  
2322  0.126582  
2342  0.823795  
2355  0.445876  
2381  0.600000  
2382  0.472727  

[103 rows x 17 columns]

In which month was the correlation coefficient between the home team win probability and home team wins greatest?

In [31]:
for month in months:
    corrcoef = np.corrcoef( vars()[f'game_month_{month}']["win"], vars()[f'game_month_{month}']["winprob"])[0,1]
    print( f'{month}: {corrcoef}')

10: 0.4132172955401343
11: 0.3188901681703326
12: 0.3218384323878671
1: 0.5035297031511201
2: 0.3792800728400271
3: 0.41270835902083153
4: 0.4554355039974143
